### ISSUE TITLE
[Bug]: 地下城盔甲无法正常使用铁砧 Repairing mcda crashes the game

### ISSUE THREAD

**Issue by TX520131** [Rad586/Forget-Me-Not#70]
### Descripiton 简述

地下城盔甲MOD的盔甲应该正常可以通过铁砧修复和附魔，但放铁砧上是第二个无论放什么都会崩溃TAT

### Steps to reproduce. 复现问题的步骤

放铁砧上，第一个放盔甲，第二个不管放什么都会崩溃

**Comment by Rad586** [comment]
![image](https://github.com/Rad586/Forget-Me-Not/assets/99306685/b37a6849-010e-41b7-b545-8101ac078501)
![image](https://github.com/Rad586/Forget-Me-Not/assets/99306685/60e212e9-50b4-4189-a36a-b895beb3ec2c)
![image](https://github.com/Rad586/Forget-Me-Not/assets/99306685/8248642b-dc82-4ebd-b08c-89e7203a5f67)
Should be fixed in 2.5.0+

**Comment by TX520131** [comment]
找到问题了，我下载的1.19.3的2.1.2版本安装包，换成1.19.2的2.5.0版本就正常了
